language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

before_install:
- if [[ "$TRAVIS_PHP_VERSION" > "5.5" ]]; then composer require satooshi/php-coveralls; else composer require satooshi/php-coveralls '~1.0'; fi;
- composer require codeclimate/php-test-reporter

before_script:
- mkdir build/logs

after_script:
- php vendor/bin/coveralls
- php vendor/bin/test-reporter
